services:
    Sf4\Api\Services\TagAwareCacheAdapter:
        class: Sf4\Api\Services\TagAwareCacheAdapter
        lazy: true
        calls:
            - method: init
    Sf4\Api\Services\CacheAdapterInterface: '@Sf4\Api\Services\TagAwareCacheAdapter'

    Sf4\Api\Repository\RepositoryFactory:
        class: Sf4\Api\Repository\RepositoryFactory
        lazy: true
        arguments:
            $entityManager: '@Doctrine\ORM\EntityManagerInterface'
            $entities: []

    Sf4\Api\RequestHandler\RequestHandlerInterface:
        class: Sf4\Api\RequestHandler\RequestHandler
        lazy: true
        calls:
            -   method: setEntityManager
                arguments:
                    - '@Doctrine\ORM\EntityManagerInterface'
            -   method: setTranslator
                arguments:
                    - '@Symfony\Component\Translation\TranslatorInterface'
            -   method: setDispatcher
                arguments:
                    - '@Symfony\Component\EventDispatcher\EventDispatcherInterface'
            -   method: setRepositoryFactory
                arguments:
                    - '@Sf4\Api\Repository\RepositoryFactory'
            -   method: setCacheAdapter
                arguments:
                    - '@Sf4\Api\Services\CacheAdapterInterface'

    Sf4\Api\EventSubscriber\RequestSubscriber:
        class: Sf4\Api\EventSubscriber\RequestSubscriber
        lazy: true
        tags: ['kernel.event_subscriber']
        arguments:
            - '@Sf4\Api\RequestHandler\RequestHandlerInterface'

    Sf4\Api\Routing\ApiLoader:
        tags: [routing.loader]
